import random as rand

SHARD_IDS = [0, 1]
NUM_VALIDATORS = 10
VALIDATOR_NAMES = []
for i in range(NUM_VALIDATORS):
    VALIDATOR_NAMES.append(i)
VALIDATOR_WEIGHTS = {}
for v in VALIDATOR_NAMES:
    VALIDATOR_WEIGHTS[v] = rand.uniform(5, 25)

VALIDATOR_SHARD_ASSIGNMENT = {}
SHARD_VALIDATOR_ASSIGNMENT = {0: [], 1: []}
for v in VALIDATOR_NAMES:
    if v <= NUM_VALIDATORS/2:
        VALIDATOR_SHARD_ASSIGNMENT[v] = 0
        SHARD_VALIDATOR_ASSIGNMENT[0].append(v)
    else:
        VALIDATOR_SHARD_ASSIGNMENT[v] = 1
        SHARD_VALIDATOR_ASSIGNMENT[1].append(v)

TTL_CONSTANT = 3

NUM_TRANSACTIONS = 50

# Experiment parameters
REPORTING = True
NUM_ROUNDS = 1000
NUM_WITHIN_SHARD_RECEIPTS_PER_ROUND = 15
NUM_BETWEEN_SHARD_RECEIPTS_PER_ROUND = 5
MEMPOOL_DRAIN_RATE = 1
REPORT_INTERVAL = 1
PAUSE_LENGTH = 0.000001

# Instant broadcast
FREE_INSTANT_BROADCAST = False

# Validity check options
VALIDITY_CHECKS_WARNING_OFF = True
VALIDITY_CHECKS_OFF = True
